Repository AY2021S1-CS2103T-W10-4/tp, pull requests merged in 2020-09, with the labels that each got.

#35 Update AboutUs, UG, DG with the relevant parts.
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/linkedink.png
Labels: type.AboutUs, type.DG, type.UG

#36 Update AboutUs page for chan-j-d
  build.gradle
  docs/AboutUs.md
  docs/images/chan-j-d.png
  gradle/wrapper/gradle-wrapper.properties
Labels: type.AboutUs

#38 Update contact Edit and Find commands in UserGuide
  docs/UserGuide.md
Labels: type.UG

#39 Update DeveloperGuide to include Edit and Find use cases
  docs/DeveloperGuide.md
Labels: type.DG

#40 Update README for Athena
  README.md
Labels: type.README

#56 Change 'AddressBook' instances to 'Athena' in DG
  docs/DeveloperGuide.md
Labels: type.DG

#57 Fix formatting and grammatical issues in user guide
  docs/UserGuide.md
Labels: type.UG

#58 v1.1 UG grammer updates
  docs/UserGuide.md
Labels: type.UG
