Repository AY2021S1-CS2103T-W10-4/tp, pull requests merged in 2020-10, with the labels that each got.

#71 Update edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#74 Updated UG for consistency
  docs/UserGuide.md
Labels: type.UG

#67 Add addEvent command, Updated UI to display events
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Calendar.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyCalendar.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/Description.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.High

#73 Add SearchEvent and ListEvent features
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListEventCommand.java
  src/main/java/seedu/address/logic/commands/SearchEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchEventCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/DescriptionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#81 Update outdated mentions to AddressBook
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: bug, severity.Medium, severity.VeryLow

#78 Fix add wildcard tag bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: priority.Medium

#86 Add introduction message
  src/main/java/seedu/address/logic/commands/IntroCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/IntroWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/IntroWindow.fxml
Labels: priority.High

#88 Fix discrepancies in user guide method naming
  docs/UserGuide.md
Labels: bug, severity.High, type.UG

#91 Add deleteEvent feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteEventCommandParser.java
Labels: enhancement, priority.High

#94 Add editEvent feature
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.High

#117 Create tag manager
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/TagManager.java
  src/main/java/seedu/address/model/tag/TagManagerImpl.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTagManagerIntegrationTest.java
  src/test/java/seedu/address/model/tag/TagManagerImplTest.java
Labels: enhancement, priority.High

#128 Update ClearCommand and relevant classes to ClearContactCommand
  src/main/java/seedu/address/logic/commands/ClearContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#131 Update test cases
  src/main/java/seedu/address/logic/parser/FindEventCommandParser.java
  src/main/java/seedu/address/model/event/DescriptionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/EventUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: bug, enhancement, priority.Low, severity.VeryLow

#132 Standardise tag capitalization
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.High

#133 Enable assertion in gradle file
  build.gradle
  src/main/java/seedu/address/model/tag/TagManagerImpl.java
Labels: priority.High

#141 Update references in developer guide
  docs/DeveloperGuide.md
Labels: bug, severity.Low, type.DG

#142 Update Model module component of DeveloperGuide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.DG

#143 Create supertag support - View and List tag commands have been added
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/ViewTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ContactTagIntegrationManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/tag/ReadOnlyTagTree.java
  src/main/java/seedu/address/model/tag/TagManager.java
  src/main/java/seedu/address/model/tag/TagManagerImpl.java
  src/main/java/seedu/address/model/tag/TagTree.java
  src/main/java/seedu/address/model/tag/TagTreeImpl.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableTagTree.java
  src/main/java/seedu/address/storage/JsonTagTreeStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TagTreeStorage.java
  src/test/data/JsonSerializableTagTreeTest/invalidTagTree.json
  src/test/data/JsonSerializableTagTreeTest/sampleValidTagTree.json
  src/test/data/JsonTagTreeStorageTest/invalidTagTree.json
  src/test/data/JsonTagTreeStorageTest/notJsonFormatTagTree.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTagCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTagCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTagManagerIntegrationTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ContactTagIntegrationManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/tag/TagTreeImplTest.java
  src/test/java/seedu/address/storage/JsonSerializableTagTreeTest.java
  src/test/java/seedu/address/storage/JsonTagTreeStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TagTreeUtil.java
Labels: enhancement, priority.High

#150 Add Clear Event feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ClearEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: enhancement, priority.Low

#152 Add ability to read from and save calendar data to calendar.json file
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CalendarStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonCalendarStorage.java
  src/main/java/seedu/address/storage/JsonSerializableCalendar.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/EventCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListTagCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.High

#153 Fix USAGE_MESSAGES not being in the right format
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/PermaSortContactCommand.java
  src/main/java/seedu/address/logic/commands/SortContactCommand.java
  src/main/java/seedu/address/logic/commands/SortEventCommand.java
  src/main/java/seedu/address/logic/commands/ViewTagCommand.java
Labels: bug, severity.Medium

#160 Update GUI and error messages
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/contacts/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/ClearContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/PermaSortContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/SortContactCommand.java
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/events/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/events/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/events/SortEventCommand.java
  src/main/java/seedu/address/logic/commands/general/ExitCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultPanel.fxml
Labels: enhancement, priority.High

#162 Update user guide
  docs/Ui.png
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: bug, severity.High

#164 Update Tag UserGuide
  docs/UserGuide.md
Labels: type.UG

#163 Create add super tag command
  src/main/java/seedu/address/logic/commands/tags/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/tags/AddTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ContactTagIntegrationManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/TagManager.java
  src/main/java/seedu/address/model/tag/TagManagerImpl.java
  src/main/java/seedu/address/model/tag/TagTree.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/contacts/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/tags/AddTagCommandTest.java
  src/test/java/seedu/address/logic/parser/tags/AddTagCommandParserTest.java
  src/test/java/seedu/address/model/ContactTagIntegrationManagerTest.java
  src/test/java/seedu/address/model/tag/TagTreeImplTest.java
Labels: priority.High

#165 Enhance SortEvent Command
  src/main/java/seedu/address/logic/commands/events/SortEventCommand.java
  src/main/java/seedu/address/logic/comparators/EventComparator.java
  src/main/java/seedu/address/logic/parser/events/AddEventCommandParser.java
Labels: enhancement, priority.Medium

#170 Create edit tag command
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/tags/EditTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/tags/EditTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/TagTreeImpl.java
  src/main/java/seedu/address/model/tag/exceptions/TagCyclicDependencyException.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/tags/EditTagCommandTest.java
  src/test/java/seedu/address/logic/parser/tags/EditTagCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTreeImplTest.java
Labels: enhancement, priority.High

#166 Create delete tag command
  src/main/java/seedu/address/commons/core/booleaninput/BooleanInput.java
  src/main/java/seedu/address/logic/commands/tags/DeleteTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/tags/DeleteTagCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/commons/core/booleaninput/BooleanInputTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/tags/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/parser/tags/DeleteTagCommandParserTest.java
Labels: enhancement, priority.High

#175 Update user guide
  docs/UserGuide.md
  docs/images/DeleteSingleTagPic.png
Labels: priority.High, type.UG

#177 Fix bugs involving EditContactCommand
  src/main/java/seedu/address/logic/commands/contacts/EditContactCommand.java
  src/main/java/seedu/address/logic/parser/contacts/EditContactCommandParser.java
  src/test/java/seedu/address/logic/commands/contacts/EditContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#176 Fix ViewTagCommand to match userguide
  src/main/java/seedu/address/logic/commands/tags/ViewTagCommand.java
Labels: priority.High

#172 Add event person association
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/events/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/events/EditEventCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/association/FauxPerson.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedFauxPerson.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventListCard.fxml
  src/test/java/seedu/address/logic/commands/AddEventCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/AddEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: enhancement, priority.High

#178 Update User Guide: Sort Event Command
  docs/UserGuide.md
Labels: type.UG

#181 Fix intro command bug
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/general/IntroCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug, severity.VeryLow

#180 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ContactTagDiagram.puml
  docs/diagrams/DeleteTagSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelClassOverviewDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ContactTagDiagram.png
  docs/images/DeleteTagSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelClassOverviewDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.DG

#182 Update version number for release
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#185 Add section about displaying introduction window to DG
  docs/DeveloperGuide.md
  docs/diagrams/IntroSequenceDiagram.png
  docs/diagrams/IntroSequenceDiagram.puml
Labels: type.DG

#184 Add instructions for reminder related functions
  docs/UserGuide.md
Labels: documentation

#183 Fix and update event related UG components
  docs/UserGuide.md
  docs/images/ug-images/add-event-behaviour.png
  docs/images/ug-images/clear-event-behaviour.png
  docs/images/ug-images/edit-event-behaviour-after.png
  docs/images/ug-images/edit-event-behaviour-before.png
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
Labels: documentation, priority.High
