Repository AY2021S1-CS2103T-W10-4/tp, pull requests merged in 2020-11, with the labels that each got.

#222 Allow events with same description but different time to be added
  src/main/java/seedu/address/model/event/Event.java
Labels: enhancement, priority.Medium

#224 Update time displayed in GUI to be more human readable (2nd PR)
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/ui/EventCard.java
  src/test/java/seedu/address/model/event/TimeTest.java
Labels: enhancement, priority.Medium

#228 Update day difference to be difference by dates, rather than absolute time
  src/main/java/seedu/address/model/event/Time.java
Labels: bug, severity.Low

#227 Update delete -c and delete -e to accept a list of indexes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/contacts/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/events/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/contacts/DeleteContactCommandParser.java
  src/main/java/seedu/address/logic/parser/events/DeleteEventCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
  src/test/java/seedu/address/logic/commands/contacts/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/contacts/DeleteContactCommandParserTest.java
Labels: enhancement, priority.Medium

#230 Update delete -c and edit -c to delete/edit associated FauxPersons
  src/main/java/seedu/address/model/Calendar.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
Labels: enhancement, priority.High

#231 Set limit for number of displayed associated persons per event
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/ui/EventCard.java
Labels: enhancement, priority.Low

#235 Update add -e and edit -e so they don't result in clashing events
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/model/Calendar.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: bug, severity.Medium

#236 Refactor parseIndexes and code that uses it
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/contacts/DeleteContactCommandParser.java
  src/main/java/seedu/address/logic/parser/events/DeleteEventCommandParser.java
Labels: priority.Low

#239 Update tutorial commands to include command type
  src/main/java/seedu/address/ui/IntroWindow.java
Labels: bug, severity.Medium

#240 Implement multiple bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/contacts/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/ClearContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/PermaSortContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/SortContactCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: bug, enhancement

#243 Add new test cases for parsed commands
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement, priority.Low

#242 Fix delete person tag bug
  docs/UserGuide.md
  src/main/java/seedu/address/model/ContactTagIntegrationManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/TagTree.java
  src/main/java/seedu/address/model/tag/TagTreeImpl.java
  src/test/java/seedu/address/model/ContactTagIntegrationManagerTest.java
  src/test/java/seedu/address/model/tag/TagTreeImplTest.java
Labels: enhancement, priority.High, type.UG

#244 Fix edit contact command bug
  src/main/java/seedu/address/logic/commands/contacts/EditContactCommand.java
  src/test/java/seedu/address/logic/commands/contacts/EditContactCommandTest.java
Labels: priority.Medium

#245 Add tag description specifying tag format
  docs/UserGuide.md
Labels: type.UG

#237 Edit Time class to allow more time input formats
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
  src/main/java/seedu/address/model/event/Time.java
Labels: enhancement, priority.Medium

#247 Update add event command to throw the correct exception
  src/main/java/seedu/address/logic/commands/events/AddEventCommand.java
Labels: bug, severity.High

#251 Add Hendey's draft PPP
  docs/team/linkedink.md
Labels: documentation

#252 Add chan-j-d ppp file
  docs/team/chan-j-d.md
Labels: documentation

#253 Add Illio's PPP
  docs/team/fyshhh.md
Labels: documentation

#254 Add Links for PRs in Sol's PPP
  docs/team/solkim-83.md
Labels: documentation

#257 Add find tag command
  src/main/java/seedu/address/commons/core/booleaninput/BooleanInput.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/tags/FindTagCommand.java
  src/main/java/seedu/address/logic/commands/tags/ListTagCommand.java
  src/main/java/seedu/address/logic/commands/tags/ViewTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/contacts/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/tags/FindTagCommandParser.java
  src/main/java/seedu/address/model/tag/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagTree.java
  src/main/java/seedu/address/model/tag/TagTreeImpl.java
  src/main/java/seedu/address/model/util/TagUtil.java
  src/test/data/JsonSerializableTagTreeTest/sampleValidTagTree.json
  src/test/java/seedu/address/logic/commands/tags/FindTagCommandTest.java
  src/test/java/seedu/address/logic/commands/tags/ListTagCommandTest.java
  src/test/java/seedu/address/logic/parser/tags/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/ContactTagIntegrationManagerTest.java
  src/test/java/seedu/address/model/tag/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TagTreeUtil.java
Labels: enhancement, priority.Low

#260 Add more time formats
  docs/UserGuide.md
  src/main/java/seedu/address/model/event/Time.java
Labels: enhancement, priority.Low

#262 Update clear -c to remove person from events
  src/main/java/seedu/address/logic/commands/contacts/ClearContactCommand.java
Labels: bug, severity.High

#258 Add view event command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandWord.java
  src/main/java/seedu/address/logic/commands/events/ViewEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/events/ViewEventCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement, priority.Medium

#265 Amend formatting errors on DG
  docs/DeveloperGuide.md
Labels: type.DG

#261 Amend minor errors in UG and java docs/comments
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/contacts/PermaSortContactCommand.java
  src/main/java/seedu/address/logic/commands/events/SortEventCommand.java
  src/main/java/seedu/address/model/event/Time.java
  src/main/java/seedu/address/model/person/Address.java
Labels: documentation, priority.Low, type.UG

#271 Final Draft of Sol's PPP
  docs/team/solkim-83.md
Labels: documentation

#272 Update user guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.UG

#274 Final Version of Sol's PPP
  docs/team/solkim-83.md
Labels: documentation

#276 Update contacttagintegrationmanager component of dg
  docs/DeveloperGuide.md
  docs/diagrams/DeleteTagSequenceDiagram.puml
  docs/images/DeleteTagSequenceDiagram.png
  docs/images/tagtree-test-tree.png
Labels: type.DG

#278 Fix minor issues with developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
Labels: type.DG

#279 Add images to my sections of the user guide
  docs/UserGuide.md
  docs/images/ug-images/contactBehaviourImages/edit-contact-image.png
  docs/images/ug-images/contactBehaviourImages/find-contact-image.png
  docs/images/ug-images/tagBehaviourImages/add-tag-image.png
  docs/images/ug-images/tagBehaviourImages/delete-tag-image.png
  docs/images/ug-images/tagBehaviourImages/edit-tag-image.png
  docs/images/ug-images/tagBehaviourImages/list-tag-image.png
  docs/images/ug-images/tagBehaviourImages/view-tag-image.png
Labels: type.UG

#282 Update certain aspects of UG
  docs/UserGuide.md
  docs/images/ug-images/tagBehaviourImages/list-tag-image.png
Labels: type.UG

#281 Add images for Event features & Edit Command display messages
  docs/UserGuide.md
  docs/images/ug-images/eventBehaviourImages/find-event-behaviour.png
  docs/images/ug-images/eventBehaviourImages/list-event-behaviour-after.png
  docs/images/ug-images/eventBehaviourImages/sort-event-behaviour-1.png
  docs/images/ug-images/eventBehaviourImages/sort-event-behaviour-2.png
  src/main/java/seedu/address/logic/commands/contacts/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/PermaSortContactCommand.java
  src/main/java/seedu/address/logic/commands/contacts/SortContactCommand.java
  src/main/java/seedu/address/logic/commands/events/EditEventCommand.java
  src/main/java/seedu/address/logic/commands/events/FindEventCommand.java
  src/main/java/seedu/address/logic/commands/events/ListEventCommand.java
  src/main/java/seedu/address/logic/commands/events/SortEventCommand.java
Labels: documentation, type.UG

#283 Update dev guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/IntroSequenceDiagram.png
  docs/diagrams/IntroSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/IntroSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/index.md
  src/main/java/seedu/address/model/util/TagUtil.java
Labels: documentation, type.DG

#286 Revert "Add test case for remind event command"
  src/test/java/seedu/address/logic/commands/reminders/RemindEventCommandTest.java
Labels: bug, severity.High

#285 Update Developer Guide
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/ContactTagDiagram.puml
  docs/diagrams/DeleteTagSequenceDiagram.puml
  docs/diagrams/ViewTagTreeActivityDiagram.puml
  docs/images/ContactTagDiagram.png
  docs/images/DeleteTagSequenceDiagram.png
  docs/images/ViewTagTreeActivityDiagram.png
Labels: type.DG

#284 Update Illio's PPP
  docs/team/fyshhh.md
Labels: documentation

#291 Update model include reminders
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassOverviewDiagram.puml
  docs/diagrams/style.puml
  docs/images/ModelClassOverviewDiagram.png
Labels: priority.High, type.DG

#290 Update badges to match Athena repo
  docs/index.md
Labels: priority.High

#292 Add find tag example image
  docs/UserGuide.md
  docs/images/ug-images/tagBehaviourImages/find-tag-image.png
Labels: documentation, type.UG

#295 Update PPP with line break
  docs/team/fyshhh.md
Labels: documentation

#296 Update PPP and UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/linkedink.md
Labels: documentation

#297 Update my ppp and about us
  docs/AboutUs.md
  docs/team/chan-j-d.md
Labels: documentation

#299 Update SortEvent Activity Diagram Label
  docs/diagrams/SortEventActivityDiagram.puml
  docs/images/SortEventActivityDiagram.png
Labels: type.DG

#294 Update DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddEventAttendeesDiagram.puml
  docs/diagrams/EditedEventAttendeesDiagram.puml
  docs/images/AddEventAttendeesDiagram.png
  docs/images/EditedEventAttendeesDiagram.png
Labels: documentation

#302 Update stylesheet to automatically include page breaks
  docs/assets/css/style.scss
Labels: type.DG, type.UG

#313 Highlight parts written by me
  docs/UserGuide.md
Labels: documentation, type.UG

#314 Label sections of UG
  docs/UserGuide.md
Labels: documentation, type.UG

#315 Update contributions for my sections
  docs/UserGuide.md
Labels: priority.High, type.UG

#317 Add page breaks
  docs/UserGuide.md
Labels: documentation, type.UG

#319 Add line breaks to space out pages
  docs/UserGuide.md
Labels: documentation, type.UG

#318 Update UG with labels and some tips
  docs/UserGuide.md
Labels: documentation

#320 Amend UG
  docs/UserGuide.md
Labels: documentation
